[tool.poetry]
name = "leetcode"
version = "0.1.0"
description = "Leetcode solutions"
authors = ["Alberto Murillo"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-cov = "^4.1.0"
pytest-benchmark = "^4.0.0"
black = "^24.2.0"
isort = "^5.13.2"
flake8 = "^7.0.0"
pylint = "^3.1.0"
pyright = "^1.1.353"
mypy = "^1.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
py_version = 39
